name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  TAG: ${{ github.sha }}
  GO_VERSION: 1.23.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: make test
      - name: Tag release
        run: echo ${{ env.TAG }}
